live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "command"

[mouse]
hide_when_typing = true

[scrolling]
history = 20000
multiplier = 20

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 18
y = 16
