ln -sv ~/dotfiles/clash/config.yaml ~/.config/clash
ln -sv ~/dotfiles/zsh/.zshrc  ~
ln -sv ~/dotfiles/starship/starship.toml ~/.config
ln -sv ~/dotfiles/tmux ~/.config
ln -sv ~/dotfiles/.gitconfig ~
ln -sv ~/dotfiles/kitty   ~/.config
ln -sv ~/dotfiles/nvim ~/.config
ln -sv ~/dotfiles/yazi  ~/.config
ln -sv ~/dotfiles/rofi  ~/.config
ln -sv ~/dotfiles/waybar  ~/.config
