# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 500

[username]
disabled = true
[hostname]
disabled = true
[container]
disabled = true

[line_break]
disabled = false

[directory]
truncation_length = 8       # 最长显示路径级别
truncate_to_repo = true

[kubernetes]
format = "[$context:$namespace](blue) "
disabled = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[cmd_duration]
disabled = false
min_time = 4
show_milliseconds = false
style = "yellow"

# git
[git_branch]
symbol = " "
