#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="CaskaydiaCove Nerd Font Mono" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)
INNER_PADDINGS=16

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=40
  color=$TRANSPARENT
  border_color=$TRANSPARENT
  border_width=2
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  topmost=window
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown

  padding_right=$PADDINGS
  padding_left=$PADDINGS

  icon.font="$FONT:Regular:14.0"
  icon.color=$ICON_COLOR
  icon.padding_right=$PADDINGS

  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.shadow.drawing=on
  label.shadow.distance=2
  label.shadow.color=0xff000000

  background.color=$BG0
  background.height=30
  background.corner_radius=15
  background.border_width=2
  blur_radius=2

  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.color=$BG0
  popup.background.border_color=$WHITE
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
# source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/media.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/input_source.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/weather.sh"

sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
