[font]
family = "Noto Sans CJK SC"
style = "Regular"

[color-palette]
palette = [
    "#ff0000",  # 红色（默认选中）
    "#00ffff",  # 青色
    "#008000",  # 绿色
    "#ffd700",  # 金色
    "#ff1493",  # 深粉
    "#ffffff",  # 白色
]
