preload = /home/lordhamster/Sync/Wallpapers/cult of the lamp1.jpg
#if more than one preload is desired then continue to preload other backgrounds
preload = /home/lordhamster/Sync/Wallpapers/cult of the lamp2.png
# .. more preloads

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = ,contain:/home/lordhamster/Sync/Wallpapers/cult of the lamp1.jpg

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off

